#### 1. Replace all odd numbers in array with -2


Use the array given below

arr = np.array([0, 31, 42, 43, 34, 45, 26, 27, 38, 94, 65, 78, 76])

In [3]:
import numpy as np
arr = np.array([0, 31, 42, 43, 34, 45, 26, 27, 38, 94, 65, 78, 76])
arr[arr % 2 == 1] = -2

In [4]:
arr

array([ 0, -2, 42, -2, 34, -2, 26, -2, 38, 94, -2, 78, 76])

#### 2. Write a program to calculate the sum of each column

Use the array given below: (or create your own array)

A = [[1, 4, 8], [5, 7, 3], [9, 14, 2]]

In [8]:
A = np.array([[1, 4, 8], [5, 7, 3], [9, 14, 2]])
A.sum(axis=0)

array([15, 25, 13])

	
#### 3.  Write a code to get the element-wise remainder of an array after division by 8

In [14]:
num = [42, 87, 90, 14, 32, 75, 61, 80, 92]

# convert the list to array
num_np = np.array(num)

num_np % 8

array([2, 7, 2, 6, 0, 3, 5, 0, 4])